name: example_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter: 
    sdk: flutter
  http: ^1.0.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  flutter_bloc: ^7.0.0
  url_launcher: ^6.0.3
  mongo_dart: ^0.9.1
  provider: ^6.0.5

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - images/
    
    
